"""Initial migration

Revision ID: 491812872a08
Revises: 
Create Date: 2025-08-03 14:57:50.332527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491812872a08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribute_city'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_country'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_email'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_first_name'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_gitHub_link'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_id'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_last_name'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_linkedIn_link'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_state'), table_name='contribute')
    op.drop_index(op.f('ix_contribute_zip_code'), table_name='contribute')
    op.drop_table('contribute')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribute',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gitHub_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedIn_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contribute_pkey'))
    )
    op.create_index(op.f('ix_contribute_zip_code'), 'contribute', ['zip_code'], unique=False)
    op.create_index(op.f('ix_contribute_state'), 'contribute', ['state'], unique=False)
    op.create_index(op.f('ix_contribute_linkedIn_link'), 'contribute', ['linkedIn_link'], unique=False)
    op.create_index(op.f('ix_contribute_last_name'), 'contribute', ['last_name'], unique=False)
    op.create_index(op.f('ix_contribute_id'), 'contribute', ['id'], unique=False)
    op.create_index(op.f('ix_contribute_gitHub_link'), 'contribute', ['gitHub_link'], unique=False)
    op.create_index(op.f('ix_contribute_first_name'), 'contribute', ['first_name'], unique=False)
    op.create_index(op.f('ix_contribute_email'), 'contribute', ['email'], unique=False)
    op.create_index(op.f('ix_contribute_country'), 'contribute', ['country'], unique=False)
    op.create_index(op.f('ix_contribute_city'), 'contribute', ['city'], unique=False)
    # ### end Alembic commands ###
